version: "3.7"

services:
  database:
    build: ./monolith-db
    hostname: database
    restart: always
    environment:
      POSTGRES_PASSWORD: This1s_pr0jecT
    volumes:
      - ./monolith-db/data:/var/lib/postgresql/data
    ports:
      - 2345:5432

  api:
    build: ./monolith-backend
    hostname: api
    restart: always
    volumes:
      - ./monolith-backend/src:/usr/app/src
    environment:
      WAIT_HOSTS: database:5432
      PORT: 4000
      HOSTNAME: 0.0.0.0

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./monolith-nginx/conf.d:/etc/nginx/conf.d
      - ./monolith-nginx/access.log:/var/log/nginx/monolith-blog.access.log
    ports:
      - 80:80
