version: "3.7"

services:
  database:
    build: ./monolith-db
    container_name: monolith_database
    hostname: database
    restart: always
    environment:
      POSTGRES_PASSWORD: This1s_pr0jecT
    volumes:
      - ./monolith-db/data:/var/lib/postgresql/data
    ports:
      - 2345:5432

  api:
    build: ./monolith-backend
    container_name: monolith_api
    hostname: monolith_api
    restart: always
    volumes:
      - ./monolith-backend/src:/usr/app/src
    environment:
      WAIT_HOSTS: database:5432
      PORT: 4200
      HOSTNAME: 0.0.0.0
    ports:
      - 4200:4200
