version: "3.7"

services:
  database:
    build: ./monolith-db/
    container_name: monolith_database
    hostname: database
    restart: always
    environment:
      POSTGRES_PASSWORD: This1s_pr0jecT
    volumes:
      - ./monolith-db/data:/var/lib/postgresql/data
    ports:
      - 2345:5432

  api:
    build:
      context: ./monolith-backend
      dockerfile: Dockerfile-CI
    container_name: monolith_api
    hostname: monolith_api
    restart: always
    volumes:
      - ./monolith-backend/src:/usr/app/src
    environment:
      WAIT_HOSTS: database:5432
      PORT: 4000
      HOSTNAME: 0.0.0.0
      PGUSER: postgres
      PGHOST: database
      PGPASSWORD: This1s_pr0jecT
      PGDATABASE: blog
      PGPORT: 5432
      SECRET: randomserial
