name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: This1s_pr0jecT
      PGDATABASE: blog
      PGPORT: 5432
      SECRET: randomserial

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build docker compose
        run: docker-compose up -d
      - name: list docker process
        run: docker-compose ps
      - name: list env in monolith_api
        run: docker exec monolith_api printenv
      - name: run test
        run: docker exec monolith_api yarn jest --forceExit --detectOpenHandles --maxWorkers=10
