name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: add typescipt-cli
        run: yarn global add typescript
      - name: build production
        run: cd monolith-backend/ &&\
          yarn &&\
          yarn build &&\
          cd ..
      - name: build docker compose
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: list docker process
        run: docker-compose ps
      - name: list env in monolith_api
        run: docker exec monolith_api printenv
      - name: run test
        run: docker exec monolith_api yarn jest --forceExit --detectOpenHandles --maxWorkers=10
